### ISSUE TITLE
Sound is not playing

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#225]
## Expected Behavior

The [sound](https://raw.githubusercontent.com/threema-ch/threema-web/master/public/sounds/notification.mp3) plays…

## Current Behavior

No sound is played.

## Possible Solution

Possibly a change in the CSP is needed?

## Steps to Reproduce (for bugs)

0. Activate the setting for the sound.
1. Send a message to ECHOECHO.

## Your Environment

* Threema Web version: 1.2.0, self-hosted
* Browser name and version: Firefox 53.0.2
* Operating system and version: Debian 8

**Comment by dbrgn** [comment]
> Possibly a change in the CSP is needed?

Yes, you're right.

**Comment by rugk** [comment]
I have not tested whether this also affects web.threema.ch, but in any case, could you please comment here, which change is actually needed.

**Comment by dbrgn** [comment]
You need the `media-src 'self' data:` CSP rule.

Additionally, there's a media file URL bug fixed in 23a75c47794f785b4056823c6f4428eabf7a0128. A patch release will follow today.

**Comment by dbrgn** [comment]
Fixed version is deployed to web.threema.ch.

**Comment by rugk** [comment]
It still does not work after updating to v1.2.1. No sound when I write to ECHOECHO.

**Comment by dbrgn** [comment]
You don't get a notification if the chat is already open and focussed :)

**Comment by rugk** [comment]
I also tried it with switching the tab, so that a notification is shown, but no sound is played.

**Comment by dbrgn** [comment]
You can test it on web.threema.ch, where I confirmed that the notification sound works. If it doesn't, it must be an issue with your setup. Check your debug console for potential problems.

**Comment by rugk** [comment]
Yeah, you were right. Issue solved.
