### ISSUE TITLE
First opened chat loads infinitely/very long

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-web#247]
## Expected Behavior

Chat loads.

## Current Behavior

Always spinning, always loading, 

## Steps to Reproduce (for bugs)

IMHO the first chat I open after (re)connection a session, seems to take a very long time to load.
Actually, when I click on another chat during this loading time, this chat is there immediately. Afterwards I can click on the previous chat, I originally intended to load and the chat history is also loaded quite fast.

## Your Environment

* Threema Web version: 1.2.1
* Threema for Android version: 3.14.2000352
* Threema for Android source: Pirate Bay (I love this selection option here :laughing:, but I think it was:) Google Play/Beta
* Browser name and version: Firefox 53.0.3
* Operating system and version: Linux

**Comment by ovalseven8** [comment]
Can confirm this issue.

**Comment by ovalseven8** [comment]
Perhaps it helps for finding the bug:
If you click on the input field at the bottom, it stops loading and the messages are displayed.

**Comment by ontheair81** [comment]
I can confirm this issue. This happens very often due to [#184](https://github.com/threema-ch/threema-web/issues/184).
And I can confirm too, that clicking in the input field brings Threema Web back to life.

**Comment by dbrgn** [comment]
>  If you click on the input field at the bottom, it stops loading and the messages are displayed.

Thanks @ovalseven8 and @ontheair81, that's actually a helpful hint. It means that the data was loaded, but somehow the AngularJS digest loop does not run. Any event should fix that (e.g. a new incoming message).

**Comment by rugk** [comment]
I could not stop it this way. In my case it only stopped when clicking there **and** typing some text in there.

**Comment by ovalseven8** [comment]
Perhaps a regression, I think in some previous version the chat did not load infinitely. But not sure.

**Comment by ontheair81** [comment]
Right, this bug seems to be introduced in 1.2.x and is still there in 1.3.1. In older versions chats loaded quick.

**Comment by dbrgn** [comment]
I'm pretty sure that this is a regression introduced in #243.

**Comment by ovalseven8** [comment]
>Perhaps it helps for finding the bug:
If you click on the input field at the bottom, it stops loading and the messages are displayed.

Seems like just clicking anywhere is enough and you don't necessarily have to click on the input field.

**Comment by lgrahl** [comment]
I'm experiencing the same issue and it looks like the message request is
not being sent, i.e. there's no *Sending message request for contact
ECHOECHO with message id null* in the log. Only if I click on another
conversation and then click on the ECHOECHO conversation again, the request
is being sent.

**Comment by fichtennadel** [comment]
I can confirm this, too (Web 1.4.1, App 3.17.2000363 Google Play).

Switching chats is a workaround: if chat 1 hangs, selecting chat 2 and switching back to 1 then shows messages in chat 1. 

And it's related to loading the chat history: if there is a new message and the chat is not yet open, the new message is shown immediately after opening the chat, but loading the history takes a lot of time.

**Comment by lgrahl** [comment]
Firefox only as far as I can tell. So, this can either be a timing problem or a difference in data channel implementations. Adding `RTCDataChannel.send` calls to the log output and mapping them to the various states may reveal the problem.

**Comment by ontheair81** [comment]
Just want to mention that this bug (introduced in WebClient 1.2.x) is still present in current version 1.6.0.

Tested on:
Firefox ESR 52.3.0, 64Bit, Win7
Android 6.0.1
Threema App 3.2.2000373

**Comment by lgrahl** [comment]
@dbrgn @sillych It's not an issue with data channels. `requestMessages` is not being called when clicking on a conversation (let that be contact *A*). However, once you request another conversation (let that be contact *B*), then both *A* and *B* are being requested. Looks to me as if the request is not being propagated properly.

I can reproduce this 100% of times on FF 55.0.2 x64 Ubuntu.

**Comment by ontheair81** [comment]
This problem seems to be solved with current version 1.6.1. Anybody can confirm?
Great, thank you!

**Comment by rugk** [comment]
No, still reproducible. And still clicking somewhere makes it work.

**Comment by fichtennadel** [comment]
version 1.6.2, still reproducible

**Comment by ovalseven8** [comment]
With Firefox Quantum (v57) I cannot reproduce this anymore, can you?

**Comment by dbrgn** [comment]
Hasn't happened to me in a while (but it did when I used the nightly version that lead to the current v57). Maybe something was fixed in the meantime.

**Comment by ontheair81** [comment]
Right, works fine with Firefox Quantum. But, of course, it is still present in Firefox ESR.

**Comment by lgrahl** [comment]
It (very rarely) happens in Chrome, too. So, this issue isn't fixed.
