### ISSUE TITLE
Threema app shows I am connected with session although I am not

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#327]
Just found this. Don't know if there is a way to make it reproducible.

![screenshot_20170907-221548](https://user-images.githubusercontent.com/8258609/30183740-d1de36c6-941b-11e7-8b9d-903065e488c9.png)

## Your Environment
* Threema Web version: 1.5.0
* Threema for Android version: 3.19.2000369

**Comment by ovalseven8** [comment]
Found a way to make it reproducible:

1. Go the the "Threema Web" menu in the app
2. Reconnect to session

Now, if I immediately stop the session everything is ok. However:

3. Wait some time until your smartphone turns of light/is locked
4. Stop session (in browser!)

Now, if you unlock your phone you'll see that the icon in the "Threema Web" menu is still green although one is not connected anymore.

Could you reproduce?

**Comment by rugk** [comment]
I think I experienced this issue, too. When you then try to start the connection again the icon in the app always turns red and goes crazy more or less. In any case then I always had to force-close Threema, and sometimes even create a new connection (i.e. scan a new QR code) and delete the old one, which was still showing the red warning icon.

**Comment by dbrgn** [comment]
There were a few state transitions that weren't covered in the current release, resulting in strange behavior and/or crashes. This is probably fixed in the current development version and will be released in the next beta.

**Comment by ovalseven8** [comment]
> This is probably fixed in the current development version and will be released in the next beta.

Just installed the new beta (3.19.2000370), but issue is NOT fixed.

**Comment by dbrgn** [comment]
Sorry, I referred to the comment by @rugk. It's possible that the state displayed at the right of a session is not always accurate yet. (We refactored the entire session handling code, so there's a lot to test and debug, and the efforts were mostly focussed on voice calls until this week. So give us some time :wink:)

**Comment by ovalseven8** [comment]
Yeah, yeah, no problem. Just wanted to inform you. :wink: 

I guess also in previous versions of Threema this problem occurred. So it's probably not related to your refactorings.

**Comment by ovalseven8** [comment]
Issue is still reproducible with Threema 4.0-beta2.

**Comment by ovalseven8** [comment]
Issue is still reproducible with Threema 4.2.

**Comment by dbrgn** [comment]
Should be resolved with one of the next versions of Threema (depending on how long we need to test the changes).
