### ISSUE TITLE
<Contact> cannot receive files

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#70]
For contacts that have not ever sent me a file, nor do I have sent them a file, I receive an error message when trying to send a file: `<Contact> cannot receive files`. However, sending a file via the app works fine. And after having done that, I can send further files via the web client.

**Comment by sillych** [comment]
With which version (Threema App -> Settings -> About Threema) can you reproduce this problem?

**Comment by lgrahl** [comment]
App: 3.01.2000340
Web Client: 1.0.1

**Comment by sillych** [comment]
Thanks! How do you create this contact (adding via Web-Client, adding the identity in the app, scanning the qr code, contact sync)?

**Comment by lgrahl** [comment]
These contacts have been added a long time ago, way before file messages have been added. Some via contact sync, others via identity (ECHOECHO for example). I can try adding a new contact and see if it makes a difference if you want me to?

**Comment by sillych** [comment]
Yes please :+1:  .... fyi: ECHOECHO cannot receive files

**Comment by lgrahl** [comment]
Eh... alright, good point about ECHOECHO. But *luckily* I still have contacts left where it doesn't work as described.
Added a new contact, works fine for new contacts. @dbrgn told me has an idea why it doesn't work for me. :)

**Comment by Kurisutian** [comment]
It's the same here for me. So it's definitely not only you (lgrahl) who's affected.

**Comment by dbrgn** [comment]
@Kurisutian were you a beta tester? If not, my assumption was wrong.

**Comment by Kurisutian** [comment]
@dbrgn unfortunately I wasn't. I would have loved to be one (still am) but Threema still isn't looking for more Android beta testers, afaik. ;)

**Comment by lgrahl** [comment]
I had to recover a backup from a pretty old version some time ago. Maybe this information helps.

**Comment by sillych** [comment]
@lgrahl thanks. i think the problem are the synchronized contacts. we will fix this in the next release

**Comment by ovalseven8** [comment]
Is this fixed with Threema 3.1?

**Comment by dbrgn** [comment]
Should be fixed in the app. If the problem still persists, feel free to add a comment.

**Comment by lgrahl** [comment]
Last time I checked this problem still occurred. Let me check that.

**Comment by lgrahl** [comment]
Yeah, I still have that issue in at least one group.

**Comment by dbrgn** [comment]
> Yeah, I still have that issue in at least one group.

What does that mean? You can't send a file to the group? Is it possible from the app? Is there someone in the group that cannot receive files?

**Comment by lgrahl** [comment]
> You can't send a file to the group?

Yes

> Is it possible from the app?

Yes

> Is there someone in the group that cannot receive files?

No

**Comment by dbrgn** [comment]
@lgrahl could you maybe try current master? I added some debug log statements, that might help us to find the source of the problem.

**Comment by lgrahl** [comment]
> Cannot send message: Feature level mismatch: 1 < 3

**Comment by rugk** [comment]
Now I experience this issue too…

**Comment by dbrgn** [comment]
>  It even happened in a group chat once (one contact cannot receive the files), but when sending the file to the contact directly, it worked.

Did it work in the group chat again after you sent the file to the contact directly?

**Comment by rugk** [comment]
Yes, it worked afterwards.

**Comment by lgrahl** [comment]
@rugk Now, kill the app and try again in the web client after you've restarted the app. Does it fail again?

**Comment by rugk** [comment]
Yes, it worked with one:
> Cannot send message: Feature level mismatch: 0 < 3  angular.js:14199:18
>14:11:12.385 «[…]» kann noch keine Dateien erhalten.  angular.js:14199:18
>	consoleLog/< […]/node_modules/angular/angular.js:14199:18
>	ConversationController/this.submit/</</</< […]/dist/app.js:11950:37
>14:11:12.387 uncaught exception: undefined

1.4.0-gh

However, I also noticed that (now?) I cannot send the file into the group or single chat either. It's always one contact breaking it.

**Comment by alexanderadam** [comment]
I have exactly the same issue.
In my case it's a contact with umlaut in the name (if it make any difference).
In the error message the umlaut is converted to html entities which aren't interpreted as such but directly shown.

**Comment by joelfischerr** [comment]
As far as I know ECHOECHO can't receive files.

**Comment by rugk** [comment]
They can receive pictures. Actually I just tried to send a picture (both via Copy/Paste and drag and drop.).

**Comment by dbrgn** [comment]
Pictures are a separate, older message type than generic files. ECHOECHO cannot receive files at the moment. Pictures on the other hand should work.

**Comment by rugk** [comment]
Yes, but this error here was shown for pictures anyway. (Maybe it was "cannot receive pictures", did not look so closely).

**Comment by dbrgn** [comment]
@rugk can you still reproduce this? if yes, maybe we could send you a debug version of the app with more logging in order to track down the root cause? (unfortunately I haven't been able to reproduce the issue in a long time...)

**Comment by rugk** [comment]
The new closed beta of Threema seems to fix it.

**Comment by dbrgn** [comment]
@rugk thanks for verifying! I hope we can finally close this :slightly_smiling_face: 

The fix will land in the next Android release.
