### ISSUE TITLE
Message is sent directly after choosing Japanese IME candidate in macOS Safari

### ISSUE THREAD

**Issue by jeifour** [threema-ch/threema-web#777]
## Expected Behavior
When I use Threema Web on Safari on macOS and I compose a message in Japanese, I want the text input box to behave similar to other system text boxes. For example, Whatsapp Web, Skype or virtually any other chat client or text box with a submit button I encountered in my daily computer usage until now.

## Current Behavior
When composing a message, after you finished writing the first word and you have chosen a candidate that you want to send, you hit Enter to select the candidate. This leads to the message being sent immediately, before you are able to enter any other words or complete your sentence that you were trying to write.

## Possible Solution
It seems like the Threema Web client has an input text box that behaves differently from other text boxes and listens globally for "Enter" presses. When one uses an IME, pressing Enter doesn't generally mean that they are finished composing a message. It's a necessity to pick a certain candidate out of multiple possible words with the same pronunciation.

## Steps to Reproduce (for bugs)
1. Open Threema Web in Safari (12.0.3) on macOS (10.14.3).
2. Make sure you have activated Kotoeri IME (built-in macOS Japanese input method) and switch to, for instance, Hiragana input.
3. Input any word. For example どうよう (douyou). Press the space bar repeatedly to choose the actual word that you're trying to input. (Alternatively arrow keys could be used.) For example here we chould choose 動揺.
4. Now press Enter to select the word. While that will indeed select the word, it will also lead the message beint sent preemptively.

Here's a short video that tries to show the problem:
![threemaweb_ime](https://user-images.githubusercontent.com/3247063/54649192-843c8d00-4aa9-11e9-944f-223f3081c34e.gif)

## Your Environment
* Threema Web version: 2.1.7
* Threema App version: unlikely to be relevant (4.1.3 iOS)
* Browser name and version: Safari 12.0.3
* Computer operating system and version: macOS 10.14.3
* Smartphone operating system and version: unlikely to be relevant (iOS 12.1.4, iPhone SE)

**Comment by dbrgn** [comment]
Thanks for the report. I also found that problem this week when working on #773.

Definitely a bug. The enter key should not trigger sending when it's part of a composition event.

**Comment by dbrgn** [comment]
Should get fixed in #773.

**Comment by ovalseven8** [comment]
@jeifour: You can try out https://web-beta.threema.ch.

**Comment by jeifour** [comment]
> @jeifour: You can try out https://web-beta.threema.ch.

Thanks. I only tested this right now, but it unfortunately doesn't solve the problem in Safari (12.1.1 on macOS 10.14.5). On the same machine it works fine in Firefox (67.0.4) and Chrome (75.0.3770.100).

I also tested in a new private window in Safari to make sure it's not some weird caching of old code, but the behavior doesn't change from before. It's still exactly like in my original post.

**Comment by lgrahl** [comment]
Reopening then.

**Comment by dbrgn** [comment]
So when you start typing, pick an entry from the popup and then press enter, the text is not submitted.

If you start typing and press enter without selecting an entry from the popup, the text *is* submitted.

I'm not very familiar with Japanese IMEs, but I assume that in both cases the text should not be submitted, as long as its still underlined.

**Comment by jeifour** [comment]
> So when you start typing, pick an entry from the popup and then press enter, the text is not submitted.
> 
> If you start typing and press enter without selecting an entry from the popup, the text _is_ submitted.
> 
> I'm not very familiar with Japanese IMEs, but I assume that in both cases the text should not be submitted, as long as its still underlined.

The text is submitted immediately when I click Enter, regardless of my interaction with the popup. I'm using the built-in Japanese IME of macOS, btw (which is called Kotoeri). I'll test a bit more extensively with the beta version and report back if I notice anything interesting.

The text should only be submitted after an Enter-click if there's no "pending input", so to speak. Unfortunately I'm also not an expert on IMEs, I just use them frequently. I'll try to also test with some other languages.

**Comment by dbrgn** [comment]
Yep, we are checking composition events triggered by the IME. Unfortunately the order of those events differs between browsers, it's all a bit of a mess.

We'll try to figure out a way to properly detect the end of a composition sequence, so that the enter-to-submit behavior can be suppressed while a composition is ongoing.

**Comment by dbrgn** [comment]
For the record, event order in Firefox when pressing enter:

1. onKeyDown (composed=true, isComposing=true)
2. onCompositionEnd
3. onKeyUp (composed=true, isComposing=false)

Event order in Safari:

1. onCompositionEnd
2. onKeyDown (composed=true, isComposing=false)
3. onKeyUp (composed=true, isComposing=false)

This should be solvable with a `compositionHasJustEnded` flag that is set in `onCompositionEnd` and reset in `onKeyUp`. :roll_eyes:
